// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coscup2017_grpc_proto/save_text/save.proto
// Original file comments:
// Proto file for saving gcp speech to text recoginzed result.
//
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Coscup2017Demo.Saving {
  public static partial class SaveTextService
  {
    static readonly string __ServiceName = "coscup2017demo.saving.SaveTextService";

    static readonly grpc::Marshaller<global::Coscup2017Demo.Saving.SaveResultRequest> __Marshaller_SaveResultRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Coscup2017Demo.Saving.SaveResultRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Coscup2017Demo.Saving.SaveResultResponse> __Marshaller_SaveResultResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Coscup2017Demo.Saving.SaveResultResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Coscup2017Demo.Saving.SaveResultRequest, global::Coscup2017Demo.Saving.SaveResultResponse> __Method_SaveResult = new grpc::Method<global::Coscup2017Demo.Saving.SaveResultRequest, global::Coscup2017Demo.Saving.SaveResultResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SaveResult",
        __Marshaller_SaveResultRequest,
        __Marshaller_SaveResultResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Coscup2017Demo.Saving.SaveReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of SaveTextService</summary>
    public abstract partial class SaveTextServiceBase
    {
      public virtual global::System.Threading.Tasks.Task SaveResult(global::Coscup2017Demo.Saving.SaveResultRequest request, grpc::IServerStreamWriter<global::Coscup2017Demo.Saving.SaveResultResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for SaveTextService</summary>
    public partial class SaveTextServiceClient : grpc::ClientBase<SaveTextServiceClient>
    {
      /// <summary>Creates a new client for SaveTextService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SaveTextServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for SaveTextService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SaveTextServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SaveTextServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SaveTextServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Coscup2017Demo.Saving.SaveResultResponse> SaveResult(global::Coscup2017Demo.Saving.SaveResultRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SaveResult(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Coscup2017Demo.Saving.SaveResultResponse> SaveResult(global::Coscup2017Demo.Saving.SaveResultRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SaveResult, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SaveTextServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SaveTextServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SaveTextServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SaveResult, serviceImpl.SaveResult).Build();
    }

  }
}
#endregion
